Added control 1 a & b, 2 a, 6 a, 15 a checks
US-EPA-CAMD/easey-monitor-plan-api pull request #348
Opened 2023-03-01 19:57 UTC by RobertB-CVP

The scope of this pull request is to address the following Checks:

[ECMPS Monitoring Plan Check Specifications](https://ecmps.camdsupport.com/documents/ECMPS%20Monitoring%20Plan%20Check%20Specifications%202022%20Q1.pdf)

 CONTROL-1 - Control Parameter Code Valid (Result A, B)
 CONTROL-2 - Control Code Valid (Result A)
 CONTROL-6 - Control Retire Date Valid (Result A)
 CONTROL-15 - Duplicate Unit Control Records (Result A)

2023-03-01 20:28 UTC, subrataroyCVP requested changes
I am creating a PR for MP Checks. Please follow that instead of import checks.

2023-03-01 23:07 UTC, subrataroyCVP requested changes

2023-03-01 23:07 UTC, subrataroyCVP commented on src/dtos/unit-control.dto.ts
>    @IsInDbValues(
```suggestion
  @IsValidCode(
```

2023-03-01 23:07 UTC, subrataroyCVP commented on src/dtos/unit-control.dto.ts
>    @IsInDbValues(
```suggestion
  @IsValidCode(
```

2023-03-01 23:07 UTC, subrataroyCVP commented on src/dtos/unit-control.dto.ts
> +        return `${args.property} The value for ${args.value} in the Unit Control record ${args.property} is invalid`;
```suggestion
        return `The value for ${args.value} in the Unit Control record ${args.property} is invalid`;
```

2023-03-01 23:07 UTC, subrataroyCVP commented on src/dtos/unit-control.dto.ts
> +      return `${args.property} The value for ${args.value} in the Unit Control record  ${args.property} must be string value of "0" or "1"`;
```suggestion
      return `The value for ${args.value} in the Unit Control record  ${args.property} must be string value of "0" or "1"`;
```

2023-03-01 23:07 UTC, subrataroyCVP commented on src/dtos/unit-control.dto.ts
> +      return `${args.property} The value for ${args.value} in the Unit Control record ${args.property} must be a valid ISO date format yyyy-mm-dd`;
```suggestion
      return `The value for ${args.value} in the Unit Control record ${args.property} must be a valid ISO date format yyyy-mm-dd`;
```

2023-03-01 23:07 UTC, subrataroyCVP commented on src/dtos/unit-control.dto.ts
> +      return `${args.property} The value for ${args.value} in the Unit Control record ${args.property} must be a valid ISO date format yyyy-mm-dd`;
```suggestion
      return `The value for ${args.value} in the Unit Control record ${args.property} must be a valid ISO date format ${DATE_FORMAT}`;
```

2023-03-01 23:07 UTC, subrataroyCVP commented on src/dtos/unit-control.dto.ts
> +      return `${args.property} The value for ${args.value} in the Unit Control record  ${args.property} must be string value of "0" or "1"`;
```suggestion
      return `The value for ${args.value} in the Unit Control record  ${args.property} must be string value of "0" or "1"`;
```

2023-03-01 23:07 UTC, subrataroyCVP commented on src/dtos/unit-control.dto.ts
> +      return `${args.property} The value for ${args.value} in the Unit Control record ${args.property} must be a valid ISO date format yyyy-mm-dd`;
```suggestion
      return `The value for ${args.value} in the Unit Control record ${args.property} must be a valid ISO date format ${DATE_FORMAT}`;
```

2023-03-01 23:07 UTC, subrataroyCVP commented on src/monitor-plan-workspace/monitor-plan-checks.service.ts
> +                monitorLocation.id,
```suggestion
                monitorLocation.unitRecordId,
                monitorLocation.id,
```

These wont be provided by user.

2023-03-02 20:47 UTC, subrataroyCVP requested changes
Need Small Change.

2023-03-02 20:47 UTC, subrataroyCVP commented on src/entities/unit-control-codes.entity.ts
> +export class unitControlCodes extends BaseEntity {
```suggestion
export class UnitControlCode extends BaseEntity {
```

2023-03-02 20:47 UTC, subrataroyCVP commented on src/dtos/unit-control.dto.ts
> +  @IsValidCode(unitControlCodes, {
```suggestion
  @IsValidCode(UnitControlCode, {
```

2023-03-02 21:09 UTC, subrataroyCVP requested changes

2023-03-02 21:09 UTC, subrataroyCVP commented on src/dtos/unit-control.dto.ts
> +  @IsValidCode(ParameterCode, {
```suggestion
  @IsValidCode(ParameterCode, {
```

Previously it was doing look up for parameter on camdecmpsmd.vw_unitcontrol_master_data_relationships.
Now you are doing against parameterCode table. Also in the checks it says `Locate ParameterCode in the Control Code lookup table.`

2023-03-02 21:11 UTC, subrataroyCVP commented on src/dtos/unit-control.dto.ts
> +  @IsValidCode(ParameterCode, {
Follow the DB Script.

2023-03-03 19:58 UTC, jordanfontainecvp approved these changes, later dismissed

2023-03-03 20:31 UTC, subrataroyCVP approved these changes

2023-03-03 20:36 UTC, merged