Feature/5597 mp api schema updates
US-EPA-CAMD/easey-monitor-plan-api pull request #480
Opened 2023-09-11 12:58 UTC by jeffreyaggrey

## Pull Request

2023-09-11 13:29 UTC, subrataroyCVP requested changes
`unitOfStandard` need to be updated to `unitofStandard`.

2023-09-11 13:29 UTC, subrataroyCVP commented on src/dtos/monitor-plan-update.dto.ts
>    @Type(() => UnitStackConfigurationBaseDTO)
missed to update `unitStackConfigurations` and `locations`

2023-09-11 18:59 UTC, billmiller13 commented on src/component-workspace/component.service.ts
> +    private readonly analyzerRangeDataervice: AnalyzerRangeWorkspaceService,
Misspelled analyzerRangeDataService

2023-09-11 20:07 UTC, billmiller13 reviewed
Looks good except for the one comment I left where you misspelled something

2023-09-12 20:28 UTC, subrataroyCVP approved these changes
All the DTO changes looks good. Tested with few monitorPlans, Import and Export working as expected.

2023-09-12 21:42 UTC, subrataroyCVP commented
@fanwari1 Merging the PR. Let @jeffreyaggrey know about the changes, if any.

2023-09-12 21:43 UTC, merged