fixed location not found on export
US-EPA-CAMD/easey-monitor-plan-api pull request #481
Opened 2023-09-11 22:40 UTC by shahbazkhan1999

2023-09-12 20:01 UTC, sdhawan16 requested changes

2023-09-12 20:01 UTC, sdhawan16 commented on src/monitor-plan/monitor-plan.controller.ts
> +      params.planId[0],
Instead of indexing this, MonitorPlanParamsDTO can be modified so the planId doesn't have the isArray: true property. The transform statement can also be removed since the parameter is not a multi-select but rather a string field.

2023-09-12 20:08 UTC, subrataroyCVP requested changes
I have reviewed the issue. only change is needed in `MonitorPlanParamsDTO`,  need to remove the transform for planId `@Transform(({ value }) => value.split('|').map((id: string) => id.trim()))`

2023-09-12 20:18 UTC, sdhawan16 commented on src/monitor-plan/monitor-plan.repository.ts
> +    .innerJoinAndSelect('plan.plant', 'plant', 'plan.fac_id = plant.fac_id')
Since this is not needed to resolve the issue, this change can be removed.

2023-09-12 21:53 UTC, subrataroyCVP requested changes

2023-09-12 21:53 UTC, subrataroyCVP commented on src/monitor-plan/monitor-plan.repository.ts
fix formatting.

2023-09-12 21:53 UTC, subrataroyCVP commented on src/dtos/monitor-plan-params.dto.ts
> +  @ApiProperty()
Please add the description beck.

2023-09-12 22:01 UTC, subrataroyCVP commented
Update branch also.

2023-09-13 20:32 UTC, subrataroyCVP approved these changes
LGTM

2023-09-13 20:36 UTC, sdhawan16 approved these changes
lgtm

2023-09-13 20:42 UTC, merged